apiVersion: v1
kind: ConfigMap
metadata:
  name: biggshots-config
  namespace: biggshots-demo
data:
  DB_HOST: "biggshots-postgres"
  DB_PORT: "5432"
  DB_NAME: "biggshots_demo2"
  DB_USER: "biggshots_demo2_user"
  REDIS_URL: "redis://biggshots-redis:6379"
  MAIL_HOST: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_SECURE: "false"
  SITE_URL: "https://k3-demo.biggshotsmedia.com"
  ADMIN_EMAIL: "hello@biggshotsmedia.com"
  SCHEDULER_INTERVAL_MS: "1800000"
  ENVIRONMENT: "wsl2-k3s-demo-namespace"
