FROM nginx:alpine

COPY . /usr/share/nginx/html
COPY nginx.k8s.conf /etc/nginx/conf.d/default.conf

# Remove files that shouldn't be served as static content
RUN rm -f /usr/share/nginx/html/Dockerfile \
          /usr/share/nginx/html/nginx.conf \
          /usr/share/nginx/html/nginx.k8s.conf \
          /usr/share/nginx/html/Dockerfile.k8s

EXPOSE 80
