apiVersion: v1
kind: Secret
metadata:
  name: biggshots-secret
  namespace: biggshots
type: Opaque
stringData:
  DB_PASSWORD: "your_db_password"
  MAIL_USER: "thephotographerltd@gmail.com"
  MAIL_PASS: "pymy olhw nkca bhms"
  JWT_SECRET: "your_jwt_secret"
  SESSION_SECRET: "your_session_secret"
